### ISSUE TITLE
Document about the training and test

### ISSUE THREAD

**Issue by lijie2552** [microsoft/BatteryML#13]
Could you provide more details about what are the label and features for each model?

**Comment by agiamason** [comment]
We are currently working on refining the documentation for our BatteryML project, and we will share a comprehensive article with you once it's ready. In the meantime, I'll provide a brief answer to your question:

Our BatteryML project currently supports labels such as Remaining Useful Life (RUL), and we will soon update it to include State of Health (SOH) as well. The latest version of  baseline.ipynb showed the results of multiple models on tasks with the RUL label. Each of these models utilizes different features. For instance, the variance model of the paper "Data-driven prediction of battery cycle life before capacity degradation" employs the log variance of ∆Q<sub>100−10</sub>(V). This is just one example of the various features used by the models in our project. 

Currently, you can refer to the code for more information. The features can be found in the `BatteryML/src/feature` path, while the labels are located in the `BatteryML/src/label` path. Additionally, you can find the configuration used for the models in the baseline.ipynb document within the `BatteryML/configs/baselines` directory.

We hope this information helps, and we'll keep you informed as we continue to enhance our documentation and project capabilities.
