### ISSUE TITLE
RMSE Values

### ISSUE THREAD

**Issue by abdalluhahmed** [microsoft/BatteryML#16]
I would like to extend my heartfelt gratitude for providing access to the diverse and intricate machine learning models dedicated to battery degradation. It is a remarkable contribution to the field and has the potential to expedite research and applications in battery technologies.

Upon meticulous review and utilization of the models, I have come across a pertinent query regarding the performance metrics of the models, specifically the Root Mean Square Error (RMSE) values. It has been observed that the RMSE values seem considerably high. Traditionally, for a model to exhibit apt predictive accuracy, lower RMSE values are desired as they signify smaller discrepancies between the predicted and observed values.

Could you please provide insights or clarifications on the rationale behind the seemingly elevated RMSE values? Understanding the inherent reasons or the context behind these values would greatly assist in interpreting the results more accurately and may provide a clearer perspective on the model’s applicability and reliability in real-world scenarios.

**Comment by fingertap** [comment]
There are many factors that can lead to high RMSE for the model.

First, if the feature is noisy and the model cannot learn effective patterns to predict degradation, the error will be high. This happens, for example, when applying the features proposed by Severson et al. to other datasets.

Second, we followed the typical pipeline of processing the battery data, which involves using the log-scale target for regression. This will reduce the difficulty for the models to regress the battery life and lead to better predictions. In other words, the performance upper bound can be higher. However, when the model makes mistakes, the `exp` operation that recovers the prediction from the log-scale will lead to large error. To avoid this, the model needs to be strong and robust.

Third, I think the data scarcity issue largely hinders the model training. The models cannot fit very well when the supervision is not sufficient. Also, there is a large space for improving feature design.

**Comment by fingertap** [comment]
Closing this.
