### ISSUE TITLE
Paper / Validation of the toolbox

### ISSUE THREAD

**Issue by alexwin9478** [microsoft/BatteryML#17]
Hi dear developers!
Thank you very much for providing this extensive toolbox. I am just getting curious, how you actually validated the models / parameterizations? Is there any paper available explaining all of this?
Thank you very much, best regards, Alex

**Comment by fingertap** [comment]
Hi @alexwin9478 , thanks!
We are currently working on the paper, which will soon be available. We are actively developing new features and incorporating new datasets. Please stay tuned! :-)
