### ISSUE TITLE
command line interface in pycharm is error

### ISSUE THREAD

**Issue by ruby0103** [microsoft/BatteryML#22]
![image](https://github.com/microsoft/BatteryML/assets/49381042/42684a4b-9ee6-4e17-bf28-75291b8551dc)

after Successfully installed BatteryML-0.0.1，I use ''batteryml download MATR /path/to/save/raw/data''commands,  The following error is displayed： 'batteryml' is not an internal or external command, nor is it a runnable program Or batch file.

**Comment by fingertap** [comment]
This is duplicated with #21 . Please track this error there.
