### ISSUE TITLE
Difference between figures in baseline.ipynb and BatteryML paper

### ISSUE THREAD

**Issue by Tian042000** [microsoft/BatteryML#25]
Hi dear developers, 

Thank you so much for providing this extensive toolbox. I have a question about the result plot that comparing the predicted RUL and the ground truth. 

In baseline.ipynb the plot value ranges from negative to positive and the colorbar label is cycle life, which is a bit strange. While in your paper, the value of cycle life seems reasonable. How you transformed the data? Did I miss anything? Is there any paper available explaining all of this? Thank you so much.

Best wishes, 
Tian

**Comment by Tian042000** [comment]
![normal](https://github.com/microsoft/BatteryML/assets/153609190/d6c97271-6fab-4341-a4aa-961c1c337f96)
<img width="315" alt="paper" src="https://github.com/microsoft/BatteryML/assets/153609190/4aa67240-0288-494c-a616-539657bb7c46">

**Comment by fingertap** [comment]
The label has been transformed by z-score, as you may find in batteryml/data/transformation/z_score.py

**Comment by Tian042000** [comment]
Thanks for your prompt reply! 

Do you mean that the plot in your paper the label has no zscore transformation? 

I'm tried to modify the setting for feature and label transformations in the model to see what is the difference, so there are 8 combinations. Every row has feature transformed by zscore or not. And as for label the first row is label by log and zscore in sequence. The second and third rows are label by zscore or log, respectively. The last row is no label transformation.  

I have two questions here. One is why there is no difference when feature is zscore transformed or not? Second is when label is not transformed at all (the last row), the prediction value is still different from yours. Could you please help to explain what is the reason? Thanks a lot. 

<img width="473" alt="0fa4db26-b7be-4fe3-9e0a-b0722a40499b" src="https://github.com/microsoft/BatteryML/assets/153609190/99c07819-0b0f-407e-a981-b620e68516da">

**Comment by fingertap** [comment]
We used z-score transformation in all our experiments. As you may find in `batteryml/data/transformation/base.py`, each data transformation has a `inverse_transform` method. So in our paper, after prediction, we mapped the predictions back to the original space. Hope this addresses your question.

**Comment by fingertap** [comment]
Closing this for now. If you find any questions on reproducing the results, feel free to reopen this issue.
