### ISSUE TITLE
Use of BatteryML for my own dataset

### ISSUE THREAD

**Issue by gupspriya** [microsoft/BatteryML#32]
I want to use BatteryML for my own data. How can I use and what changes are required?

**Comment by agiamason** [comment]
May I ask what is the cycler for your data?

**Comment by Compphsy** [comment]
Can I piggy back off of this comment and ask specifically the process using this data:

https://www.kaggle.com/datasets/patrickfleith/nasa-battery-dataset

I want to produce my own but will be using this dataset as my guide for collecting the data

**Comment by gupspriya** [comment]
Charge discharge cycle for my data is 4.2 V to 2.5V.

**Comment by agiamason** [comment]
Hi [gupspriya](https://github.com/gupspriya),
Do you have a defined cycler for your data collection such as Arbin, Neware, LANDT etc. as these cyclers export fixed format data, these we can modify the code to be compatible with your data format. But if the data format is irregular, we may not be able to provide support for the time being, maybe you can send us a data example for reference.

**Comment by agiamason** [comment]
Hi [Compphsy](https://github.com/Compphsy),
Sure, we can support nasa data, can I ask if you will collect .csv data or .mat data?

**Comment by Compphsy** [comment]
Hi,

Thank you for the quick response, the data is in csv format currently. 

This is a snippet of the data:

Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time
4.246711253516259,0.0002523886105860831,6.212696115916043,0.0002,0.0,0.0
4.246764125510136,-0.0014110647362388163,6.234018870000787,0.0002,4.262,9.36
4.039277018171289,-0.9950934118049801,6.250254735870466,1.0,3.465,23.281
4.019506433278611,-0.9967310600613466,6.3021756591391584,1.0,3.451,36.406
4.004763260680274,-0.9928446352399166,6.361644677784643,1.0,3.438,49.625
3.9928627084244077,-0.9959566094030224,6.3996923588972825,1.0,3.427,62.813
3.9823467950992972,-0.9946648032078992,6.23361305198984,1.0,3.419,75.89099999999999
3.9724578113821183,-0.9987529288284779,5.984853971653922,1.0,3.4,89.031
3.9637400413432737,-0.9941397917087201,5.857701988766819,1.0,3.391,102.14099999999999
3.9554322726766733,-0.9937968630394283,5.772313170034769,1.0,3.386,115.297
3.947905974663914,-0.9941198611582432,5.6509740843492455,1.0,3.381,128.438
3.940774900997409,-0.9951935027793659,5.571673053475088,1.0,3.376,141.578
3.933846618548325,-0.9956941482618694,5.515714320491757,1.0,3.37,154.719
3.9273923546175737,-0.9940850873517164,5.4568091229908875,1.0,3.366,167.813

**Comment by Roy027** [comment]
> Hi [gupspriya](https://github.com/gupspriya), Do you have a defined cycler for your data collection such as Arbin, Neware, LANDT etc. as these cyclers export fixed format data, these we can modify the code to be compatible with your data format. But if the data format is irregular, we may not be able to provide support for the time being, maybe you can send us a data example for reference.

Hi @agiamason , I also need to use BatteryML for my own dataset, could there be a guidance on how we can modify our irregular data to fit with your data format? Is there is guideline for the common data format? Thank you!

**Comment by fingertap** [comment]
You just need to preprocess your data into BatteryData format. You can check [our preprocess code](https://github.com/microsoft/BatteryML/blob/main/batteryml/preprocess/preprocess_SNL.py) for examples. Basically, you just need to define a process function that returns a BatteryData object given the path to your raw data.
