### ISSUE TITLE
Why skip HUST 7-5? 

### ISSUE THREAD

**Issue by myalos** [microsoft/BatteryML#36]
Thanks for sharing the code. Why skip HUST 7-5 in preprocess_HUST.py?
I found that in the data of HUST, the discharge rate in the last stage of discharging is 2, where the paper says it is 1?

**Comment by myalos** [comment]
https://github.com/HAIRLAB/Health_status_prediction/issues/3

**Comment by fingertap** [comment]
We did not skip this cell. As we commented in our code, we removed the first two cycles of that cell, as the data scale is problematic. As the cycle life of the batteries are over 1000 for HUST, these two cycles actually does not affect our analysis much.

**Comment by fingertap** [comment]
The discharge rate I think is ported from their paper. If their paper made a mistake, we probably inherited that issue too.
