### ISSUE TITLE
Why keep b3c43 battery in MATRCLOTestTrainTestSplitter ? 

### ISSUE THREAD

**Issue by myalos** [microsoft/BatteryML#37]
Thanks for sharing the code! 
In "Load Data.ipynb" of the repo https://github.com/rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation/, they removed the b3c43 battery data for the reason that it is noisy channel from batch3. I found that b3c43 in the MATRCLOTestTrainTestSplitter, and i am curious about why keep b3c43 battery in MATRCLOTestTrainTestSplitter?

**Comment by fingertap** [comment]
It is an outlier, if you use the same linear model to predict the battery life. They actually does not affect the model too much if it is put into train split when the number of batteries is more than that for MATR-1 or MATR-2. Actually by including this cell, it allows flexibility for other prediction tasks such as SoC and SoH prediction. It even allows the task of outlier detection. We follow the split unless we try to reproduce the existing studies.
