### ISSUE TITLE
Using CRUH/CRUSH/MIX for RUL

### ISSUE THREAD

**Issue by HasanTheSyrian** [microsoft/BatteryML#38]
Hello - I'm new to ML.

I have an assignment to train a model for battery RUL. Kindly answer the following questions:

How can I download CRUH/CRUSH/MIX? Do I just download the datasets they use and use them together? 

How do I get the RUL estimations? Do I have to train the model myself?

note: I'm after the dataset and its results only, not the training (though I'll use the paper and the training results as a benchmark for my University assignment)

**Comment by fingertap** [comment]
CRUH and CRUSH requires some datasets from the [Battery Archive](https://batteryarchive.org/). At the time we started to develop BatteryML, their datasets are directly download-able from their website. Nowadays you should email them to ask for the datasets. We will incorporate more data soon.
