### ISSUE TITLE
How to do the SOH estimation task?

### ISSUE THREAD

**Issue by ehappymonkey** [microsoft/BatteryML#43]
I noticed there are no example scripts for the SOH estimation task and the SOH_label_annotate.py file is empty. Only the rul prediction task script/label_annotate is provided.

**Comment by ehappymonkey** [comment]
![image](https://github.com/microsoft/BatteryML/assets/71270056/1a49c498-b80d-47da-9404-68a518ae7c45)

**Comment by ehappymonkey** [comment]
I'm also having trouble finding the SOH estimation related models. I would appreciate a lot if some guaids can be provided!

**Comment by ehappymonkey** [comment]
I'm also having trouble finding the SOH estimation related models. I would appreciate it a lot if some guides can be provided!

**Comment by agiamason** [comment]
Hi @ehappymonkey , we have developed local code for calculating State of Health (SOH) and State of Charge (SOC). However, accurate SOH measurement requires specific environmental conditions. Our current SOH estimation primarily relies on discharge capacity derived from Remaining Useful Life (RUL) data. This capacity is collected during RUL measurement, for example under a 4C current rate or multi-stage current rate. Given these constraints, we believe that our current SOH extraction code is not of high enough quality. Therefore, we are in the process of gathering more publicly available SOH and SOC data to improve and adapt our code accordingly.
Of course if you have some suggestions we would be glad to discuss the development of soh code with you!

**Comment by agiamason** [comment]
> I'm also having trouble finding the SOH estimation related models. I would appreciate it a lot if some guides can be provided!

For this problem, we're struggling with this too. You can see the soh results that we provide in the appendix of the paper, and we are currently using the linear and tree models and NN models like RUL task on our preprocessed soh data.
