### ISSUE TITLE
soh.py is empty

### ISSUE THREAD

**Issue by Roy027** [microsoft/BatteryML#48]
is soh.py supposed to be empty?

**Comment by agiamason** [comment]
Hi @Roy027 Yes, the current soh task code is still empty, we will update it as soon as possible!

**Comment by Roy027** [comment]
> Hi @Roy027 Yes, the current soh task code is still empty, we will update it as soon as possible!
Hi @agiamason thanks so much for the reply. May I also ask if currently all the model in batteryML are trained with RUL as target value? Would it be possible (in the future) to output multiple performance metric ( V, Current, Capacity ) by BatteryML ( say forecast the performance profile of battery after a few cycles? 

Glad to run the baseline.ipynb which gives a good introduction about BatteryML but hope to see more application ready example tutorials where we can use the model for really life application predictions. Thank you!

**Comment by agiamason** [comment]
Hi @Roy027,  thanks for your questions and advice.
- Currently, the BatteryML framework can only predict a single value, such as RUL or the SOH of a specific cycle.

- Your suggestion is excellent, and we highly appreciate industry-driven requirements. We genuinely hope that BatteryML can assist in real-world battery development, not just in academic research.

If possible, could you provide more details about your specific use case? This would help us better understand and develop the necessary features.

Based on your request, here is my understanding of the desired functionality. Please correct me if I am mistaken:

Feature 1: The input consists of electrical signals from the first N cycles (e.g., Voltage, Current, Capacity), and the output is the electrical signals for the M-th cycle (e.g., Voltage, Current, Capacity), where M > N.
Feature 2: The input consists of electrical signals from the first N cycles (e.g., Voltage, Current, Capacity), and the output is the Capacity for cycles M to M+k, where M > N.

- We are delighted that our notebook has helped you understand these concepts. We will also update the corresponding notebooks for SOH and SOC tasks.
