### ISSUE TITLE
share preprocessed MATR data

### ISSUE THREAD

**Issue by Spike0999** [microsoft/BatteryML#8]
To save your time for preprocessing, you may download the data I preprocessed: https://drive.google.com/drive/folders/1Ptk3l3I1JRogTEmL4FCCZxaH9MPpbwbV?usp=drive_link
FYI, due to time reasons, I only processed MATR data, the follow-up will then be update to the folder.

**Comment by fingertap** [comment]
The new CLI should be more convenient to use. Closing this.
